import  hashlib
print("md5.MD4")
print("From V7X TEAM")
text =str(input("Enter text :"))
hash_type = str(input("Entet Hash typr : "))
text = text.encode('utf-8')
hash_hash = hashlib.new(hash_type)
hash_hash.update(text)
hasher = hash_hash.hexdigest()
print (hasher)
